### ISSUE TITLE
Feature Request: Add and/or create customizable recipes

### ISSUE THREAD

**Issue by Zerleguan** [BernhardPosselt/pf2e-kingmaker-tools#1]
Hello!

Really like your kingmaker-tools, but I would wish there was an easy way to create my own recipies for the meals. Maybe this is already possible, yet I did not find it.

**Comment by BernhardPosselt** [comment]
Thank you for the issue; unfortunately I have to decline since I had to hard code recipe data in code to make it work. Implementing home brew support would require being able to read out data from the actual Recipe item which does not yet exist in the pf2e system. Due to how foundry works, I can't add that item type in a module, only in a system.

Working around this would require quite some hacks through flags and some custom UI to edit these and since it's likely to be included in the upcoming months because of the premium module, all that work will be for nothing.

**Comment by BernhardPosselt** [comment]
FYI, Foundry 11 might make this possible https://foundryvtt.com/releases/11.292

**Comment by BernhardPosselt** [comment]
Added it and published it under 0.0.18
