### ISSUE TITLE
Request: Multiple Kingdoms

### ISSUE THREAD

**Issue by Shadowbane0** [BernhardPosselt/pf2e-kingmaker-tools#55]
Whilst I know it's not a thing in the base content, but having ways to run multiple kingdoms could be useful. Either for getting baseline ideas for other kingdoms in the world (If your a masochist of a GM), or in my case, have two opposing parties with a kingdom each. (if your also a masochist of a gm).
I understand if this is a difficult request, and understand if it's not possible.

**Comment by BernhardPosselt** [comment]
I've sort of put work into my module to make this work, but it really hinges on things triggering from outside, like, which actor does the macro use to store the second kingdom on. Ultimately I've decided against doing that since it was kinda difficult.

I've thought about this in my home game and came to the conclusion that I'd probably run this in a very stripped down variant. I want the surrounding kingdoms to start pressuring the PCs by claiming land as well and will probably go for something similar to WWN's faction turns instead. Basically: I have no plans of implementing this, but I'll leave this issue open just in case.

**Comment by Shadowbane0** [comment]
Understood! I figured it was a bit much. And in fairness, one can use some online tools to handle other, non pc kingdom tools, or to run multiple PC kingdoms out of game. The tools still help with other things such as mapping said kingdom, camping, tables, and various other things. I'll go ahead and close it, since it's a much later consideration anyways and best saved for when you yourself feel like doing so.
